#!/bin/bash

######################################################################
# Safe Mode Parameters
######################################################################
set -e
set -u
set -o pipefail

######################################################################
# Set user-inputted arguments
######################################################################
# Format = /projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/1/output2/H3K4me3/CEMT_154/epi_mark_alignment/CEMT_154.treatment.keep.merged.rmdup.sorted.bam
INPUT_BAM=$1

# Format = H3K4me3_BC_Individual_1
OUTPUT_ID=$2

######################################################################
# hg38_no_alt.fa
######################################################################
REF="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/refs/hg38_no_alt.fa"

######################################################################
# Additional resources for hg38_no_alt.fa
######################################################################
CHROMINFO="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/refs/chrom_info/hg38_no_alt.chromsizes.txt"
BLACKLIST="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/genome_data/blacklists/hg38-blacklist.v2.bed"
DBSNP="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/genome_data/dbSNP/all/00-All_chr.vcf.gz"
DBSNP_SNPS="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/genome_data/dbSNP/snps/00-All_chr.snps.vcf.gz"
ALL_1KG_PHASE3_INDELS="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/genome_data/callsets/1kg/ALL.wgs.1000G_phase3.GRCh38.ncbi_remapper.20150424.shapeit2_indels_fixed.vcf.gz"
MILLS_AND_1KG_GOLD_INDELS="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/genome_data/callsets/mills_indels/resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"

######################################################################
# Set software packages employed & define dependencies
######################################################################
# Main tools
SAMTOOLS="/gsc/software/linux-x86_64-centos7/samtools-1.10/bin/samtools"
GATK="/home/ahauduc/software/gatk-4.1.4.1/gatk"
PICARD="/gsc/software/linux-x86_64-centos7/picard-tools-2.4.1/picard.jar"
BEDTOOLS="/gsc/software/linux-x86_64-centos7/bedtools-2.27.1/bin/bedtools"
BEDOPS_BIN="/gsc/software/linux-x86_64-centos7/bedops-2.4.35/bin"
BCFTOOLS="/gsc/software/linux-x86_64-centos7/bcftools-1.13/bin/bcftools"

######################################################################
# Call variants on recalibrated reads
######################################################################
# Add placeholder sample
$SAMTOOLS addreplacerg -r "@RG\tID:RG0\tLB:LB0\tPU:PU0\tSM:ALL" $INPUT_BAM -o /tmp/${OUTPUT_ID}_treatment_rg_added.bam
$SAMTOOLS index /tmp/${OUTPUT_ID}_treatment_rg_added.bam

# Create BP_RESOLUTION VCF
$GATK --java-options "-Xmx80G" HaplotypeCaller \
                               -R $REF \
                               --dbsnp $DBSNP \
                               -I /tmp/${OUTPUT_ID}_treatment_rg_added.bam \
                               -O /tmp/${OUTPUT_ID}_treatment_rg_added.vcf.gz \
                               -ERC BP_RESOLUTION \
                               --sample-name ALL

$BCFTOOLS view \
/tmp/${OUTPUT_ID}_treatment_rg_added.vcf.gz \
--regions-file /projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/notebook/alignment_analysis/data/consensus.all.spaas.rpkm.bed \
--threads 8 \
--output-type z \
--output /projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/notebook/alignment_analysis/ase/output/${OUTPUT_ID}_treatment_cis_hbtls.vcf.gz

$BCFTOOLS index --tbi /projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/notebook/alignment_analysis/ase/output/${OUTPUT_ID}_treatment_cis_hbtls.vcf.gz
