#!/bin/bash

######################################################################
# Safe Mode Parameters
######################################################################
set -e
set -u
set -o pipefail

######################################################################
# Set variables
######################################################################
# Main script to call
CALLSCRIPT="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/notebook/alignment_analysis/ase/scripts/bp_res_calling_ase_v2.bash"

# BAM folders
H3K4me3_FOLDER="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/1/output2/H3K4me3"
H3K27ac_FOLDER="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/1/output2/H3K27ac"
H3K4me1_FOLDER="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/1/output2/H3K4me1"
H3K9me3_FOLDER="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/1/output2/H3K9me3"
H3K27me3_FOLDER="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/1/output2/H3K27me3"
H3K36me3_FOLDER="/projects/epigenomics3/epigenomics3_results/users/ahauduc/arp/project/modules/1/output2/H3K36me3"

######################################################################
# Run callscript
######################################################################
# H3K4me3
# H3K4me3 BC
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_154/epi_mark_alignment/CEMT_154.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_BC_Individual_1
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_173/epi_mark_alignment/CEMT_173.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_BC_Individual_2
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_177/epi_mark_alignment/CEMT_177.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_BC_Individual_3
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_181/epi_mark_alignment/CEMT_181.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_BC_Individual_4
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_185/epi_mark_alignment/CEMT_185.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_BC_Individual_5
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_190/epi_mark_alignment/CEMT_190.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_BC_Individual_6
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_194/epi_mark_alignment/CEMT_194.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_BC_Individual_7
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_198/epi_mark_alignment/CEMT_198.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_BC_Individual_8
# H3K4me3 LP
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_155/epi_mark_alignment/CEMT_155.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LP_Individual_1
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_174/epi_mark_alignment/CEMT_174.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LP_Individual_2
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_178/epi_mark_alignment/CEMT_178.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LP_Individual_3
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_182/epi_mark_alignment/CEMT_182.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LP_Individual_4
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_186/epi_mark_alignment/CEMT_186.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LP_Individual_5
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_191/epi_mark_alignment/CEMT_191.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LP_Individual_6
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_195/epi_mark_alignment/CEMT_195.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LP_Individual_7
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_199/epi_mark_alignment/CEMT_199.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LP_Individual_8
# H3K4me3 LC
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_156/epi_mark_alignment/CEMT_156.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LC_Individual_1
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_175/epi_mark_alignment/CEMT_175.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LC_Individual_2
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_179/epi_mark_alignment/CEMT_179.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LC_Individual_3
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_183/epi_mark_alignment/CEMT_183.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LC_Individual_4
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_187/epi_mark_alignment/CEMT_187.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LC_Individual_5
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_192/epi_mark_alignment/CEMT_192.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LC_Individual_6
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_196/epi_mark_alignment/CEMT_196.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LC_Individual_7
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_200/epi_mark_alignment/CEMT_200.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_LC_Individual_8
# H3K4me3 SC
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_157/epi_mark_alignment/CEMT_157.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_SC_Individual_1
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_176/epi_mark_alignment/CEMT_176.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_SC_Individual_2
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_180/epi_mark_alignment/CEMT_180.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_SC_Individual_3
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_184/epi_mark_alignment/CEMT_184.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_SC_Individual_4
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_188/epi_mark_alignment/CEMT_188.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_SC_Individual_5
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_193/epi_mark_alignment/CEMT_193.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_SC_Individual_6
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_197/epi_mark_alignment/CEMT_197.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_SC_Individual_7
bash $CALLSCRIPT ${H3K4me3_FOLDER}/CEMT_201/epi_mark_alignment/CEMT_201.treatment.keep.merged.rmdup.sorted.bam   H3K4me3_SC_Individual_8

# H3K27ac
# H3K27ac BC
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_154/epi_mark_alignment/CEMT_154.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_BC_Individual_1
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_173/epi_mark_alignment/CEMT_173.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_BC_Individual_2
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_177/epi_mark_alignment/CEMT_177.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_BC_Individual_3
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_181/epi_mark_alignment/CEMT_181.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_BC_Individual_4
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_185/epi_mark_alignment/CEMT_185.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_BC_Individual_5
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_190/epi_mark_alignment/CEMT_190.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_BC_Individual_6
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_194/epi_mark_alignment/CEMT_194.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_BC_Individual_7
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_198/epi_mark_alignment/CEMT_198.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_BC_Individual_8
# H3K27ac LP
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_155/epi_mark_alignment/CEMT_155.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LP_Individual_1
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_174/epi_mark_alignment/CEMT_174.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LP_Individual_2
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_178/epi_mark_alignment/CEMT_178.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LP_Individual_3
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_182/epi_mark_alignment/CEMT_182.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LP_Individual_4
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_186/epi_mark_alignment/CEMT_186.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LP_Individual_5
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_191/epi_mark_alignment/CEMT_191.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LP_Individual_6
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_195/epi_mark_alignment/CEMT_195.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LP_Individual_7
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_199/epi_mark_alignment/CEMT_199.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LP_Individual_8
# H3K27ac LC
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_156/epi_mark_alignment/CEMT_156.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LC_Individual_1
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_175/epi_mark_alignment/CEMT_175.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LC_Individual_2
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_179/epi_mark_alignment/CEMT_179.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LC_Individual_3
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_183/epi_mark_alignment/CEMT_183.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LC_Individual_4
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_187/epi_mark_alignment/CEMT_187.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LC_Individual_5
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_192/epi_mark_alignment/CEMT_192.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LC_Individual_6
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_196/epi_mark_alignment/CEMT_196.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LC_Individual_7
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_200/epi_mark_alignment/CEMT_200.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_LC_Individual_8
# H3K27ac SC
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_157/epi_mark_alignment/CEMT_157.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_SC_Individual_1
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_176/epi_mark_alignment/CEMT_176.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_SC_Individual_2
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_180/epi_mark_alignment/CEMT_180.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_SC_Individual_3
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_184/epi_mark_alignment/CEMT_184.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_SC_Individual_4
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_188/epi_mark_alignment/CEMT_188.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_SC_Individual_5
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_193/epi_mark_alignment/CEMT_193.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_SC_Individual_6
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_197/epi_mark_alignment/CEMT_197.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_SC_Individual_7
bash $CALLSCRIPT ${H3K27ac_FOLDER}/CEMT_201/epi_mark_alignment/CEMT_201.treatment.keep.merged.rmdup.sorted.bam   H3K27ac_SC_Individual_8

# H3K4me1
# H3K4me1 BC
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_154/epi_mark_alignment/CEMT_154.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_BC_Individual_1
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_173/epi_mark_alignment/CEMT_173.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_BC_Individual_2
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_177/epi_mark_alignment/CEMT_177.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_BC_Individual_3
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_181/epi_mark_alignment/CEMT_181.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_BC_Individual_4
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_185/epi_mark_alignment/CEMT_185.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_BC_Individual_5
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_190/epi_mark_alignment/CEMT_190.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_BC_Individual_6
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_194/epi_mark_alignment/CEMT_194.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_BC_Individual_7
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_198/epi_mark_alignment/CEMT_198.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_BC_Individual_8
# H3K4me1 LP
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_155/epi_mark_alignment/CEMT_155.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LP_Individual_1
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_174/epi_mark_alignment/CEMT_174.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LP_Individual_2
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_178/epi_mark_alignment/CEMT_178.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LP_Individual_3
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_182/epi_mark_alignment/CEMT_182.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LP_Individual_4
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_186/epi_mark_alignment/CEMT_186.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LP_Individual_5
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_191/epi_mark_alignment/CEMT_191.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LP_Individual_6
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_195/epi_mark_alignment/CEMT_195.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LP_Individual_7
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_199/epi_mark_alignment/CEMT_199.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LP_Individual_8
# H3K4me1 LC
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_156/epi_mark_alignment/CEMT_156.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LC_Individual_1
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_175/epi_mark_alignment/CEMT_175.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LC_Individual_2
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_179/epi_mark_alignment/CEMT_179.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LC_Individual_3
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_183/epi_mark_alignment/CEMT_183.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LC_Individual_4
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_187/epi_mark_alignment/CEMT_187.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LC_Individual_5
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_192/epi_mark_alignment/CEMT_192.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LC_Individual_6
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_196/epi_mark_alignment/CEMT_196.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LC_Individual_7
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_200/epi_mark_alignment/CEMT_200.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_LC_Individual_8
# H3K4me1 SC
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_157/epi_mark_alignment/CEMT_157.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_SC_Individual_1
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_176/epi_mark_alignment/CEMT_176.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_SC_Individual_2
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_180/epi_mark_alignment/CEMT_180.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_SC_Individual_3
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_184/epi_mark_alignment/CEMT_184.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_SC_Individual_4
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_188/epi_mark_alignment/CEMT_188.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_SC_Individual_5
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_193/epi_mark_alignment/CEMT_193.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_SC_Individual_6
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_197/epi_mark_alignment/CEMT_197.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_SC_Individual_7
bash $CALLSCRIPT ${H3K4me1_FOLDER}/CEMT_201/epi_mark_alignment/CEMT_201.treatment.keep.merged.rmdup.sorted.bam   H3K4me1_SC_Individual_8

# H3K9me3
# H3K9me3 BC
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_154/epi_mark_alignment/CEMT_154.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_BC_Individual_1
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_173/epi_mark_alignment/CEMT_173.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_BC_Individual_2
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_177/epi_mark_alignment/CEMT_177.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_BC_Individual_3
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_181/epi_mark_alignment/CEMT_181.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_BC_Individual_4
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_185/epi_mark_alignment/CEMT_185.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_BC_Individual_5
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_190/epi_mark_alignment/CEMT_190.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_BC_Individual_6
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_194/epi_mark_alignment/CEMT_194.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_BC_Individual_7
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_198/epi_mark_alignment/CEMT_198.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_BC_Individual_8
# H3K9me3 LP
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_155/epi_mark_alignment/CEMT_155.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LP_Individual_1
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_174/epi_mark_alignment/CEMT_174.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LP_Individual_2
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_178/epi_mark_alignment/CEMT_178.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LP_Individual_3
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_182/epi_mark_alignment/CEMT_182.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LP_Individual_4
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_186/epi_mark_alignment/CEMT_186.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LP_Individual_5
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_191/epi_mark_alignment/CEMT_191.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LP_Individual_6
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_195/epi_mark_alignment/CEMT_195.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LP_Individual_7
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_199/epi_mark_alignment/CEMT_199.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LP_Individual_8
# H3K9me3 LC
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_156/epi_mark_alignment/CEMT_156.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LC_Individual_1
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_175/epi_mark_alignment/CEMT_175.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LC_Individual_2
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_179/epi_mark_alignment/CEMT_179.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LC_Individual_3
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_183/epi_mark_alignment/CEMT_183.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LC_Individual_4
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_187/epi_mark_alignment/CEMT_187.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LC_Individual_5
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_192/epi_mark_alignment/CEMT_192.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LC_Individual_6
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_196/epi_mark_alignment/CEMT_196.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LC_Individual_7
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_200/epi_mark_alignment/CEMT_200.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_LC_Individual_8
# H3K9me3 SC
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_157/epi_mark_alignment/CEMT_157.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_SC_Individual_1
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_176/epi_mark_alignment/CEMT_176.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_SC_Individual_2
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_180/epi_mark_alignment/CEMT_180.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_SC_Individual_3
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_184/epi_mark_alignment/CEMT_184.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_SC_Individual_4
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_188/epi_mark_alignment/CEMT_188.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_SC_Individual_5
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_193/epi_mark_alignment/CEMT_193.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_SC_Individual_6
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_197/epi_mark_alignment/CEMT_197.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_SC_Individual_7
bash $CALLSCRIPT ${H3K9me3_FOLDER}/CEMT_201/epi_mark_alignment/CEMT_201.treatment.keep.merged.rmdup.sorted.bam   H3K9me3_SC_Individual_8

# H3K27me3
# H3K27me3 BC
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_154/epi_mark_alignment/CEMT_154.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_BC_Individual_1
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_173/epi_mark_alignment/CEMT_173.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_BC_Individual_2
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_177/epi_mark_alignment/CEMT_177.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_BC_Individual_3
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_181/epi_mark_alignment/CEMT_181.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_BC_Individual_4
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_185/epi_mark_alignment/CEMT_185.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_BC_Individual_5
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_190/epi_mark_alignment/CEMT_190.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_BC_Individual_6
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_194/epi_mark_alignment/CEMT_194.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_BC_Individual_7
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_198/epi_mark_alignment/CEMT_198.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_BC_Individual_8
# H3K27me3 LP
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_155/epi_mark_alignment/CEMT_155.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LP_Individual_1
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_174/epi_mark_alignment/CEMT_174.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LP_Individual_2
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_178/epi_mark_alignment/CEMT_178.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LP_Individual_3
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_182/epi_mark_alignment/CEMT_182.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LP_Individual_4
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_186/epi_mark_alignment/CEMT_186.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LP_Individual_5
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_191/epi_mark_alignment/CEMT_191.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LP_Individual_6
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_195/epi_mark_alignment/CEMT_195.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LP_Individual_7
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_199/epi_mark_alignment/CEMT_199.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LP_Individual_8
# H3K27me3 LC
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_156/epi_mark_alignment/CEMT_156.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LC_Individual_1
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_175/epi_mark_alignment/CEMT_175.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LC_Individual_2
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_179/epi_mark_alignment/CEMT_179.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LC_Individual_3
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_183/epi_mark_alignment/CEMT_183.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LC_Individual_4
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_187/epi_mark_alignment/CEMT_187.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LC_Individual_5
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_192/epi_mark_alignment/CEMT_192.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LC_Individual_6
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_196/epi_mark_alignment/CEMT_196.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LC_Individual_7
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_200/epi_mark_alignment/CEMT_200.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_LC_Individual_8
# H3K27me3 SC
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_157/epi_mark_alignment/CEMT_157.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_SC_Individual_1
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_176/epi_mark_alignment/CEMT_176.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_SC_Individual_2
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_180/epi_mark_alignment/CEMT_180.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_SC_Individual_3
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_184/epi_mark_alignment/CEMT_184.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_SC_Individual_4
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_188/epi_mark_alignment/CEMT_188.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_SC_Individual_5
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_193/epi_mark_alignment/CEMT_193.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_SC_Individual_6
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_197/epi_mark_alignment/CEMT_197.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_SC_Individual_7
bash $CALLSCRIPT ${H3K27me3_FOLDER}/CEMT_201/epi_mark_alignment/CEMT_201.treatment.keep.merged.rmdup.sorted.bam   H3K27me3_SC_Individual_8

# H3K36me3
# H3K36me3 BC
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_154/epi_mark_alignment/CEMT_154.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_BC_Individual_1
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_173/epi_mark_alignment/CEMT_173.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_BC_Individual_2
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_177/epi_mark_alignment/CEMT_177.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_BC_Individual_3
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_181/epi_mark_alignment/CEMT_181.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_BC_Individual_4
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_185/epi_mark_alignment/CEMT_185.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_BC_Individual_5
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_190/epi_mark_alignment/CEMT_190.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_BC_Individual_6
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_194/epi_mark_alignment/CEMT_194.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_BC_Individual_7
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_198/epi_mark_alignment/CEMT_198.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_BC_Individual_8
# H3K36me3 LP
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_155/epi_mark_alignment/CEMT_155.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LP_Individual_1
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_174/epi_mark_alignment/CEMT_174.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LP_Individual_2
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_178/epi_mark_alignment/CEMT_178.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LP_Individual_3
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_182/epi_mark_alignment/CEMT_182.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LP_Individual_4
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_186/epi_mark_alignment/CEMT_186.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LP_Individual_5
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_191/epi_mark_alignment/CEMT_191.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LP_Individual_6
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_195/epi_mark_alignment/CEMT_195.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LP_Individual_7
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_199/epi_mark_alignment/CEMT_199.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LP_Individual_8
# H3K36me3 LC
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_156/epi_mark_alignment/CEMT_156.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LC_Individual_1
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_175/epi_mark_alignment/CEMT_175.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LC_Individual_2
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_179/epi_mark_alignment/CEMT_179.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LC_Individual_3
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_183/epi_mark_alignment/CEMT_183.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LC_Individual_4
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_187/epi_mark_alignment/CEMT_187.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LC_Individual_5
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_192/epi_mark_alignment/CEMT_192.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LC_Individual_6
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_196/epi_mark_alignment/CEMT_196.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LC_Individual_7
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_200/epi_mark_alignment/CEMT_200.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_LC_Individual_8
# H3K36me3 SC
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_157/epi_mark_alignment/CEMT_157.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_SC_Individual_1
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_176/epi_mark_alignment/CEMT_176.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_SC_Individual_2
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_180/epi_mark_alignment/CEMT_180.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_SC_Individual_3
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_184/epi_mark_alignment/CEMT_184.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_SC_Individual_4
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_188/epi_mark_alignment/CEMT_188.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_SC_Individual_5
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_193/epi_mark_alignment/CEMT_193.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_SC_Individual_6
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_197/epi_mark_alignment/CEMT_197.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_SC_Individual_7
bash $CALLSCRIPT ${H3K36me3_FOLDER}/CEMT_201/epi_mark_alignment/CEMT_201.treatment.keep.merged.rmdup.sorted.bam   H3K36me3_SC_Individual_8
